org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true

minecraft_version=1.21.1
loader_version=0.16.14
fabric_version=0.116.17+1.21.1
trinkets_version=3.10.0
patchouli_version=1.21.1-93-FABRIC

mod_id=weaversparadise
mod_name=Weavers Paradise
mod_license=MIT
mod_version=1.6.2.1-fabric
mod_group_id=xox.labvorty.weaversparadise
mod_authors=Vortianski
mod_description=Mod about crafting clothes and expressing yourself through said clothing
